# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da1b2b31272bdfa144aa2bf5a714aa393204d791b662bb36d12c999acbc0580b5c83c7530f3bf7cd6656b6a8746b07ba76a9dcd949017260ffc5f187a4568eb6

test:
  secret_key_base: 10cd769d339d8ebe16d022349db37569814193cd620828533f638c0c95eed25d43bcb65bc0f156b5cf5672141a591e026a428ea3398d27e423dc70fbe0e330c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
